# This workflow will run tests across different versions of node and different operating systems

name: CI

on:
  pull_request:
    branches: [ staging ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm config set @bit:registry https://node.bit.dev
    - run: npm ci
    - run: npm test
