# https://github.com/marketplace/actions/prettier-action
# Container action is only supported on Linux
# styling files with prettier.This includes adding new line.

name: CI
on:
  pull_request:
  push:
    branches:
    - staging

jobs:
  prettier:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v2.2
      with:
        prettier_options: --write **/*.{js,md,html,css,json}
